name: furnitureapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  supabase_flutter: ^2.5.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  lottie: ^3.1.0
  url_launcher: ^6.2.6
  image_picker: ^1.1.0
  razorpay_flutter: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0

flutter:

 
  uses-material-design: true

  assets:
  - assets/
  - assets/icons/
  - assets/lottie/
  - assets/fonts/  

  
  fonts:
  - family: NunitoSans
    fonts:
      - asset: assets/fonts/NunitoSans_Regular.ttf
      - asset: assets/fonts/NunitoSans_Light.ttf
        weight: 300
      - asset: assets/fonts/NunitoSans_SemiBold.ttf
        weight: 600
      - asset: assets/fonts/NunitoSans_Bold.ttf
        weight: 700
      - asset: assets/fonts/NunitoSans_ExtraBold.ttf
        weight: 800

  - family: Gelasio
    fonts:
      - asset: assets/fonts/Gelasio_Regular.ttf
      - asset: assets/fonts/Gelasio_Medium.ttf
        weight: 500
      - asset: assets/fonts/Gelasio_SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Gelasio_Bold.ttf
        weight: 700

  - family: Merriweather
    fonts:
      - asset: assets/fonts/Merriweather_Regular.ttf
      - asset: assets/fonts/Merriweather_Bold.ttf
        weight: 700
  